name: psycostat
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - bokeh

#name: example-environment
#channels:
#  - conda-forge
#dependencies:
#  - numpy
#  - psutil
#  - toolz
#  - matplotlib
#  - dill
#  - pandas
#  - partd
#  - bokeh
#  - dask
